package com.kings_gambit_151957.project1;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ArnvaldLocationChoice implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String location;

	public ArnvaldLocationChoice() {
	}

	public java.lang.String getLocation() {
		return this.location;
	}

	public void setLocation(java.lang.String location) {
		this.location = location;
	}

	public ArnvaldLocationChoice(java.lang.String location) {
		this.location = location;
	}

}