package com.kings_gambit_151957.project1;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ExamineDecision implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean examineBear;

	public ExamineDecision() {
	}

	public java.lang.Boolean getExamineBear() {
		return this.examineBear;
	}

	public void setExamineBear(java.lang.Boolean examineBear) {
		this.examineBear = examineBear;
	}

	public ExamineDecision(java.lang.Boolean examineBear) {
		this.examineBear = examineBear;
	}

}