package com.kings_gambit_151957.project1;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class GiveSword implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean GSC;

	public GiveSword() {
	}

	public java.lang.Boolean getGSC() {
		return this.GSC;
	}

	public void setGSC(java.lang.Boolean GSC) {
		this.GSC = GSC;
	}

	public GiveSword(java.lang.Boolean GSC) {
		this.GSC = GSC;
	}

}