package com.kings_gambit_151957.project1;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PopDecision implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean visitPlaceOfPower;

	public PopDecision() {
	}

	public java.lang.Boolean getVisitPlaceOfPower() {
		return this.visitPlaceOfPower;
	}

	public void setVisitPlaceOfPower(java.lang.Boolean visitPlaceOfPower) {
		this.visitPlaceOfPower = visitPlaceOfPower;
	}

	public PopDecision(java.lang.Boolean visitPlaceOfPower) {
		this.visitPlaceOfPower = visitPlaceOfPower;
	}

}