package com.kings_gambit_151957.project1;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ShrineDecision implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean examine;

	public ShrineDecision() {
	}

	public java.lang.Boolean getExamine() {
		return this.examine;
	}

	public void setExamine(java.lang.Boolean examine) {
		this.examine = examine;
	}

	public ShrineDecision(java.lang.Boolean examine) {
		this.examine = examine;
	}

}