package com.kings_gambit_151957.project1;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SupportDecision implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public SupportDecision() {
    }




}