package com.kings_gambit_151957.project1;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SupportChoice implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String decision;

	public SupportChoice() {
	}

	public java.lang.String getDecision() {
		return this.decision;
	}

	public void setDecision(java.lang.String decision) {
		this.decision = decision;
	}

	public SupportChoice(java.lang.String decision) {
		this.decision = decision;
	}

}