package com.kings_gambit_151957.project1;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Vidkaarls3Decision implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean accept;

	public Vidkaarls3Decision() {
	}

	public java.lang.Boolean getAccept() {
		return this.accept;
	}

	public void setAccept(java.lang.Boolean accept) {
		this.accept = accept;
	}

	public Vidkaarls3Decision(java.lang.Boolean accept) {
		this.accept = accept;
	}

}