package com.kings_gambit_151957.project1;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Vidkaarls1Combat implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean win;

	public Vidkaarls1Combat() {
	}

	public java.lang.Boolean getWin() {
		return this.win;
	}

	public void setWin(java.lang.Boolean win) {
		this.win = win;
	}

	public Vidkaarls1Combat(java.lang.Boolean win) {
		this.win = win;
	}

}