package com.kings_gambit_151957.project1;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Vidkaarls3Combat implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String outcome;

	public Vidkaarls3Combat() {
	}

	public java.lang.String getOutcome() {
		return this.outcome;
	}

	public void setOutcome(java.lang.String outcome) {
		this.outcome = outcome;
	}

	public Vidkaarls3Combat(java.lang.String outcome) {
		this.outcome = outcome;
	}

}